In [152]:
import pandas as pd
import numpy as np

In [153]:
df=pd.read_csv("00 customer.csv")
df.sample(5)

    age  gender   review education purchased
6    18    Male     Good    School        No
41   23    Male     Good        PG       Yes
15   75    Male     Poor        UG        No
5    31  Female  Average    School       Yes
43   27    Male     Poor        PG        No

In [154]:
print(df['review'].unique())
print(df['education'].unique())
print(df['purchased'].unique())

['Average' 'Poor' 'Good']
['School' 'UG' 'PG']
['No' 'Yes']

In [155]:
df=df.iloc[:,2:]
df.sample(5)

     review education purchased
43     Poor        PG        No
25     Good    School        No
23     Good    School        No
0   Average    School        No
28     Poor    School        No

In [156]:
x=df.iloc[:,0:2]
y=df.drop(x,axis='columns')
print(x.head())
print()
print()
print()
print(y.head())

    review education
0  Average    School
1     Poor        UG
2     Good        PG
3     Good        PG
4  Average        UG



  purchased
0        No
1        No
2        No
3        No
4        No

In [157]:
from sklearn.preprocessing import OrdinalEncoder

In [158]:
oe = OrdinalEncoder(
    categories=[
        ['Poor', 'Average', 'Good'],
        ['School', 'UG', 'PG']
    ]
).set_output(transform='pandas')

In [159]:
x_encoded = oe.fit_transform(x)

print("Original Data:")
print(x.head())

print("\nEncoded Data:")
print(x_encoded.head())

Original Data:
    review education
0  Average    School
1     Poor        UG
2     Good        PG
3     Good        PG
4  Average        UG

Encoded Data:
   review  education
0     1.0        0.0
1     0.0        1.0
2     2.0        2.0
3     2.0        2.0
4     1.0        1.0

In [160]:
from sklearn.preprocessing import LabelEncoder

In [161]:
le=LabelEncoder()
le.fit_transform(y)

/usr/local/lib/python3.13/dist-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 1, 0])